[green_agent]
agentbeats_id = "019bbc56-29c0-7642-b9e2-3208a5b17e96"
env = {GEMINI_API_KEY = "${GEMINI_API_KEY}"}

[[participants]]
agentbeats_id = "019bc33a-a396-79b1-8655-2f157fb6b7c3"
name = "dummy-gemini-2.5-pro"
env = {GEMINI_API_KEY = "${GEMINI_API_KEY}"}

[config]
# Evaluation settings
max_concurrent_rows = 5 # Number of dataset rows to process in parallel
max_rows = 20  # Number of dataset rows to process (-1 for all rows)

# Model configuration
green_agent_model = "gemini/gemini-2.5-flash-lite"  # Model used by the green agent
